using HarmonyLib;
using Kingmaker.Blueprints.JsonSystem;
using Kingmaker.Utility;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;

namespace TabletopTweaks.Config {
    public class Blueprints: IUpdatableSettings {
        [JsonProperty]
        private bool OverrideIds = false;
        [JsonProperty]
        private SortedDictionary<string, string> NewBlueprints = new SortedDictionary<string, string>();
        [JsonProperty]
        private SortedDictionary<string, string> AutoGenerated = new SortedDictionary<string, string>();

        public void OverrideSettings(IUpdatableSettings userSettings) {
            var loadedSettings = userSettings as Blueprints;
            if (loadedSettings.OverrideIds) {
                OverrideIds = loadedSettings.OverrideIds;
                loadedSettings.NewBlueprints.ForEach(entry => {
                    if (NewBlueprints.ContainsKey(entry.Key)) {
                        NewBlueprints[entry.Key] = entry.Value;
                    }
                });
            }
            loadedSettings.AutoGenerated.ForEach(entry => {
#if DEBUG
                AutoGenerated[entry.Key] = entry.Value;
#endif 
#if !DEBUG
                if (AutoGenerated.ContainsKey(entry.Key)) {
                    AutoGenerated[entry.Key] = entry.Value;
                }
#endif
            });
        }
        public string GetGUID(string name) {
            
            string Id;
            if (!NewBlueprints.TryGetValue(name, out Id)) {
#if DEBUG
                if (!AutoGenerated.TryGetValue(name, out Id)) {
                    Id = Guid.NewGuid().ToString("N");
                    AutoGenerated.Add(name, Id);
                    Main.LogDebug($"Generated new GUID: {name} - {Id}");
                } else {
                    Main.LogDebug($"WARNING: GUID: {name} - {Id} is autogenerated");
                }
#endif
            }
            return Id;
        }
        
        [HarmonyPatch(typeof(BlueprintsCache), "Init")]
        static class AutoGUID_Log_Patch {

            [HarmonyPriority(Priority.Last)]
            static void Postfix() {
                WriteBlueprints("Blueprints.json");
            }
            private  static void WriteBlueprints(string fileName) {
                string userConfigFolder = ModSettings.ModEntry.Path + "UserSettings";
                var userPath = $"{userConfigFolder}{Path.DirectorySeparatorChar}{fileName}";

                JsonSerializer serializer = new JsonSerializer {
                    NullValueHandling = NullValueHandling.Include,
                    Formatting = Formatting.Indented
                };
                using (StreamWriter sWriter = new StreamWriter(userPath))
                using (JsonWriter jWriter = new JsonTextWriter(sWriter)) {
                    serializer.Serialize(jWriter, ModSettings.Blueprints);
                }
            }
        }
    }
}
